### ISSUE TITLE
Turn our meeting notes into blog posts

### ISSUE THREAD

**Issue by alejandro5042** [IviFoundation/ivifoundation.github.io#20]
Let's use the Jekyll blogging features for content that has a time component, like meeting notes. We can organize meeting notes and news articles into categories such as `meetings` and `news`.

**Comment by joseph-mueller** [comment]
I suspect meeting notes should just be posted on SharePoint for now.  

I went ahead and deleted the ones that were over a decade old (from the website).

I suggest we just close this for now.

**Comment by alejandro5042** [comment]
Ah, I agree on _meeting notes_. What I was thinking about when opening this issue is this:

<https://www.ivifoundation.org/meetings/default.aspx>

These seem perfect for a blog. It shows that we have a long and rich history of collaborating together (even in-person!) and driving the industry forward.

What do you think about this instead?

**Comment by joseph-mueller** [comment]
Yes, that does make sense.

**Comment by joseph-mueller** [comment]
Substantially completed, see https://dev.ivifoundation.org/announcements.html

We can decide what all content we want to have there, but there are 4 things captured just to seed it.

**Comment by alejandro5042** [comment]
This is exactly what I was thinking. LGTM. Now we just need to expand on it... do we have more blog posts we could add/transform from existing content?

**Comment by alejandro5042** [comment]
Closing, leaving the filling of the blog with entries to: #97
