### ISSUE TITLE
Confirm Joe's initial decision to drop the bylaws page

### ISSUE THREAD

**Issue by joseph-mueller** [IviFoundation/ivifoundation.github.io#59]
If we keep it, we need to get latest bylaws.

Also, if we keep it should put it with whatever we keep around regarding membership.

Note that the reference to the page on about/legal should probably integrate whatever content is on the bylaws page directly instead of linking to it.

Probably deal with IP Policy similarly, although it may warrant more explanation, it could be inline on this very short page

**Comment by alejandro5042** [comment]
I agree. Let's link to the actual bylaws from Legal, and delete the existing bylaws page.

**Comment by joseph-mueller** [comment]
Clean up the legal page and just use it as the reference.
