### ISSUE TITLE
Reorganize site files/directories to reflect actual nav sttructure

### ISSUE THREAD

**Issue by joseph-mueller** [IviFoundation/ivifoundation.github.io#76]
Current layout no longer is well reflect in the directory structure.  Should go ahead and move files if we have agreement to the basic structure.

**Comment by joseph-mueller** [comment]
When doing this finally, don't forget to include the appropriate redirect_from settings so old URLs continue to work.

**Comment by alejandro5042** [comment]
Let's do this once we have an actual nav structure, in the next milestone.

**Comment by joseph-mueller** [comment]
Done last fall before site turn-on.   Did break a couple of Google forwarding addresses -- put in redirects for most of those.
