### ISSUE TITLE
First pass optimize site nav

### ISSUE THREAD

**Issue by alejandro5042** [IviFoundation/ivifoundation.github.io#9]
The first pass of generation left a site without effective navigation. Let's fix that.

**Comment by joseph-mueller** [comment]
I'm not sure exactly what the original concern was.  I suspect this is done, can you confirm?

**Comment by joseph-mueller** [comment]
Per above comment.  I think this is done.  Any other things needing to be done have their own issue (e.g., Legal and Bylaws items)
